# Generated by Django 4.0.2 on 2022-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('component_name', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('joint_dia', models.FloatField()),
                ('joint_depth', models.FloatField()),
                ('backup', models.FloatField()),
                ('gtwd', models.FloatField()),
                ('max_dop', models.FloatField()),
                ('min_dop', models.FloatField()),
                ('predicted_focus_current', models.FloatField()),
                ('predicted_beam_current', models.FloatField()),
            ],
        ),
    ]
